# Lesson 6.2 Homework 

## numPy Practice

Create the following ndarrays:
<br> 1) an ndarray out of the array, arr, given below called A1
<br> 2) a 4 by 4 ndarray made of random numbers from 3 to 15 inclusive
<br> 3) a 3 by 2 ndarray of 1s called A3

In [5]:
import numpy as np
arr = [[5,4,3],[1,2,9]]
## 1)
A1 = np.array(arr)
print(A1)
## 2)
A2 = np.random.randint(3, 16, (4,4))
print(A2)
## 3)
A3 = np.ones((3,2))
print(A3)

[[5 4 3]
 [1 2 9]]
[[ 7 15  9 14]
 [ 7 13  3 10]
 [11  4 15 14]
 [ 9  8 10  8]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


From A1 above, 
<br> 1) print the number 4
<br> 2) print the second column
<br> 3) print the 1st and 3rd column for the second row

In [7]:
## 1)
print(A1[0,1])
## 2)
print(A1[:,1])
## 3)
print(A1[1,[0,2]])

4
[4 2]
[1 9]


## Pandas Practice

Pick a Data Set from: https://data.ontario.ca/dataset?res_format=CSV
<br> 1) Read in the Data set
<br> 2) Output the First 5 rows
<br> 3) Output the types of each column
<br> 4) Output the mean of one of the numerical columns
<br> 5) Create a new column that is a function of another one

In [14]:
## 1)
import pandas as pd
data = pd.read_csv('https://data.ontario.ca/dataset/ab5f4a2b-7219-4dc7-9e4d-aa4036c5bf36/resource/05214a0d-d8d9-4ea4-8d2a-f6e3833ba471/download/percent_positive_by_agegrp.csv')

In [16]:
data.head()

DATE age_category  percent_positive_7d_avg
0  2020-05-01        0to13                   0.0340
1  2020-05-02        0to13                   0.0350
2  2020-05-03        0to13                   0.0360
3  2020-05-04        0to13                   0.0359
4  2020-05-05        0to13                   0.0355

In [17]:
## 3)
data.dtypes

DATE                        object
age_category                object
percent_positive_7d_avg    float64
dtype: object

In [18]:
## 4)
data["percent_positive_7d_avg"].mean()

0.033817009966777375

In [19]:
## 5)
data["Percent_Pos"] = data["percent_positive_7d_avg"]*100
data.tail()

DATE age_category  percent_positive_7d_avg  Percent_Pos
1500  2021-02-21          65+                   0.0168         1.68
1501  2021-02-22          65+                   0.0159         1.59
1502  2021-02-23          65+                   0.0164         1.64
1503  2021-02-24          65+                   0.0167         1.67
1504  2021-02-25          65+                   0.0164         1.64