# Lesson 6.2


## Numpy

In [33]:
## Grades example:
import numpy as np
grades = [[79, 95, 60],
 [95, 60, 61],
 [99, 67, 84],
 [76, 76, 97],
 [91, 84, 98],
 [70, 69, 96],
 [88, 65, 76],
 [67, 73, 80],
 [82, 89, 61],
 [94, 67, 88]]

gArray = np.array(grades)

gArray

array([[79, 95, 60],
       [95, 60, 61],
       [99, 67, 84],
       [76, 76, 97],
       [91, 84, 98],
       [70, 69, 96],
       [88, 65, 76],
       [67, 73, 80],
       [82, 89, 61],
       [94, 67, 88]])

Below we will access 
- test 3 grade of student 0
- grades of student 2
- grades of all students for test 1
- test 2 grades of the first three students
- mean grade of test 1
- test 2 grades for student 0 and 3

In [9]:
##test 3 grade of student 0
gArray[0,2]

60

In [8]:
##grades of student 2
gArray[2,:]

array([99, 67, 84])

In [10]:
## grades of all students for test 1
gArray[:, 0]

array([79, 95, 99, 76, 91, 70, 88, 67, 82, 94])

In [11]:
## test 2 grades of the first three students
gArray[:3, :2]

array([[79, 95],
       [95, 60],
       [99, 67]])

In [12]:
## mean grade of test 1
gArray[:, 0].mean()

84.1

In [24]:
## test 2 grades for student 0 and 3
gArray[[0,3], :2]

array([[79, 95],
       [76, 76]])

In [31]:
## sort each students test scores
np.sort(gArray, axis=1)

array([[60, 79, 95],
       [60, 61, 95],
       [67, 84, 99],
       [76, 76, 97],
       [84, 91, 98],
       [69, 70, 96],
       [65, 76, 88],
       [67, 73, 80],
       [61, 82, 89],
       [67, 88, 94]])

In [34]:
## sort each test score
np.sort(gArray, axis=0)

array([[67, 60, 60],
       [70, 65, 61],
       [76, 67, 61],
       [79, 67, 76],
       [82, 69, 80],
       [88, 73, 84],
       [91, 76, 88],
       [94, 84, 96],
       [95, 89, 97],
       [99, 95, 98]])

## Boolean indexing and Reshaping

In [44]:
## select record for female students
female = [ True, False,  True,  True, False,  True, False, False, False, False]

gArray[female, :]

array([[79, 95, 60],
       [99, 67, 84],
       [76, 76, 97],
       [70, 69, 96]])

In [45]:
## select record for those who had # <= 70 in test 3
gArray[gArray[:, 2]<70,:]

array([[79, 95, 60],
       [95, 60, 61],
       [82, 89, 61]])

In [46]:
## make all marks less than 70 be 70
gArray[gArray < 70] = 70

In [47]:
gArray.reshape((3,10))

array([[79, 95, 70, 95, 70, 70, 99, 70, 84, 76],
       [76, 97, 91, 84, 98, 70, 70, 96, 88, 70],
       [76, 70, 73, 80, 82, 89, 70, 94, 70, 88]])

## Creating ndarrays:

In [17]:
np.array([[0,1,2],[2,3,4]])

array([[0, 1, 2],
       [2, 3, 4]])

In [18]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [22]:
np.random.randint(0, 10, (3,3))

array([[0, 6, 1],
       [1, 5, 2],
       [1, 1, 4]])

## Speed of numPy 

In [53]:
x = np.arange(10000000)
%timeit sum(x)

%timeit np.sum(x)

C:\Users\cassy\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: overflow encountered in long_scalars
  """Entry point for launching an IPython kernel.


1.44 s ± 124 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
6.94 ms ± 862 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


# Pandas

Pandas will be the primary library that we use for the data analytics section of the course.  It contains high-level data structures and manipulation tools designed to make data analysis fast and easy in Python.  The core data structures that we will use are pandas series and dataframes. In this part we cover:

- Reading/Writing from/to a csv file.
- Getting basic properties of the dataframe.
- Indexing and Slicing dataframes


## Reading csv + Basic Attributes

In [78]:
import pandas as pd
data = pd.read_csv('https://data.ontario.ca/dataset/b1fef838-8784-4338-8ef9-ae7cfd405b41/resource/7fbdbb48-d074-45d9-93cb-f7de58950418/download/schoolcovidsummary.csv')
data.tail()

collected_date reported_date  current_schools_w_cases  \
103     2021-02-25    2021-02-26                      468   
104     2021-02-26    2021-03-01                      530   
105     2021-03-01    2021-03-02                      640   
106     2021-03-02    2021-03-03                      672   
107     2021-03-03    2021-03-04                      683   

     current_schools_closed  current_total_number_schools  \
103                      18                          4828   
104                      20                          4828   
105                      23                          4828   
106                      24                          4828   
107                      26                          4828   

     new_total_school_related_cases  new_school_related_student_cases  \
103                             101                                89   
104                             116                                99   
105                             262                               231   
106                             160                               138   
107                             101                                77   

     new_school_related_staff_cases  new_school_related_unspecified_cases  \
103                              12                                   0.0   
104                              15                                   2.0   
105                              30                                   1.0   
106                              21                                   1.0   
107                              21                                   3.0   

     recent_total_school_related_cases  \
103                              735.0   
104                              844.0   
105                             1072.0   
106                             1141.0   
107                             1168.0   

                        ...                       \
103                     ...                        
104                     ...                        
105                     ...                        
106                     ...                        
107                     ...                        

     recent_school_related_staff_cases  \
103                              108.0   
104                              120.0   
105                              149.0   
106                              164.0   
107                              164.0   

     recent_school_related_unspecified_cases  past_total_school_related_cases  \
103                                      7.0                           7717.0   
104                                      9.0                           7719.0   
105                                     10.0                           7741.0   
106                                     10.0                           7811.0   
107                                     13.0                           7881.0   

     past_school_related_student_cases  past_school_related_staff_cases  \
103                             5326.0                           1267.0   
104                             5328.0                           1267.0   
105                             5349.0                           1268.0   
106                             5412.0                           1274.0   
107                             5464.0                           1292.0   

     past_school_related_unspecified_cases  cumulative_school_related_cases  \
103                                 1124.0                             8452   
104                                 1124.0                             8563   
105                                 1124.0                             8813   
106                                 1125.0                             8952   
107                                 1125.0                             9049   

     cumulative_school_related_student_cases  \
103                                     5946   
104                                     

In [79]:
#There are column names
data.columns

Index(['collected_date', 'reported_date', 'current_schools_w_cases',
       'current_schools_closed', 'current_total_number_schools',
       'new_total_school_related_cases', 'new_school_related_student_cases',
       'new_school_related_staff_cases',
       'new_school_related_unspecified_cases',
       'recent_total_school_related_cases',
       'recent_school_related_student_cases',
       'recent_school_related_staff_cases',
       'recent_school_related_unspecified_cases',
       'past_total_school_related_cases', 'past_school_related_student_cases',
       'past_school_related_staff_cases',
       'past_school_related_unspecified_cases',
       'cumulative_school_related_cases',
       'cumulative_school_related_student_cases',
       'cumulative_school_related_staff_cases',
       'cumulative_school_related_unspecified_cases'],
      dtype='object')

In [80]:
#Get the dimensions of the data frame with shape
dimensions = data.shape
numRows = dimensions[0]
numRows

108

In [81]:
numCols = dimensions[1]
numCols

21

In [82]:
#Get the data type of each column
data.dtypes

collected_date                                  object
reported_date                                   object
current_schools_w_cases                          int64
current_schools_closed                           int64
current_total_number_schools                     int64
new_total_school_related_cases                   int64
new_school_related_student_cases                 int64
new_school_related_staff_cases                   int64
new_school_related_unspecified_cases           float64
recent_total_school_related_cases              float64
recent_school_related_student_cases            float64
recent_school_related_staff_cases              float64
recent_school_related_unspecified_cases        float64
past_total_school_related_cases                float64
past_school_related_student_cases              float64
past_school_related_staff_cases                float64
past_school_related_unspecified_cases          float64
cumulative_school_related_cases                  int64
cumulative

In [84]:
#We can pick out a column by referencing its name. The result is a series or one dimensional data frame
data['collected_date'].head()

0    2020-09-10
1    2020-09-11
2    2020-09-14
3    2020-09-15
4    2020-09-16
Name: collected_date, dtype: object

When you pick out a single column as we have done above the result is a series, which is essentially a one-dimensional dataframe

Note that when we slice a series, the second entry in non-inclusive.

When we pick out multiple column, as we have done above, the result is dataframe.

## Slicing and Indexing

We will be using the .loc (just labels) approach.  You can also slice with .iloc (just indicies) or .ix (indices and labels).

In [86]:
#Let's look at the data 
data.head()

collected_date reported_date  current_schools_w_cases  \
0     2020-09-10    2020-09-11                       13   
1     2020-09-11    2020-09-14                       15   
2     2020-09-14    2020-09-15                       27   
3     2020-09-15    2020-09-16                       35   
4     2020-09-16    2020-09-17                       51   

   current_schools_closed  current_total_number_schools  \
0                       0                          4828   
1                       0                          4828   
2                       0                          4828   
3                       0                          4828   
4                       1                          4828   

   new_total_school_related_cases  new_school_related_student_cases  \
0                               0                                 0   
1                               2                                 1   
2                              14                                 4   
3                              12                                 6   
4                              21                                 5   

   new_school_related_staff_cases  new_school_related_unspecified_cases  \
0                               0                                   NaN   
1                               1                                   NaN   
2                               4                                   6.0   
3                               4                                   2.0   
4                               4                                  12.0   

   recent_total_school_related_cases  \
0                                NaN   
1                                NaN   
2                                NaN   
3                                NaN   
4                                NaN   

                      ...                       \
0                     ...                        
1                     ...                        
2                     ...                        
3                     ...                        
4                     ...                        

   recent_school_related_staff_cases  recent_school_related_unspecified_cases  \
0                                NaN                                      NaN   
1                                NaN                                      NaN   
2                                NaN                                      NaN   
3                                NaN                                      NaN   
4                                NaN                                      NaN   

   past_total_school_related_cases  past_school_related_student_cases  \
0                              NaN                                NaN   
1                              NaN                                NaN   
2                              NaN                                NaN   
3                              NaN                                NaN   
4                              NaN                                NaN   

   past_school_related_staff_cases  past_school_related_unspecified_cases  \
0                              NaN                                    NaN   
1                              NaN                                    NaN   
2                              NaN                                    NaN   
3                              NaN                                    NaN   
4                              NaN                                    NaN   

   cumulative_school_related_cases  cumulative_school_related_student_cases  \
0                               13                                        4   
1                               15                                        5   
2                               29                                        9   
3                               41                                       15   
4                               62                                       20   

   cumul

In [88]:
#Pick out a single entry (using loc)
data.loc[1,"collected_date"]

'2020-09-11'

In [87]:
#Select rows and columns usng loc
data.loc[1:3, "collected_date":"current_schools_closed"]

collected_date reported_date  current_schools_w_cases  \
1     2020-09-11    2020-09-14                       15   
2     2020-09-14    2020-09-15                       27   
3     2020-09-15    2020-09-16                       35   

   current_schools_closed  
1                       0  
2                       0  
3                       0

Note that when we slice with .loc, the endpoint are inclusive.

In [129]:
#Select rows and columns usng iloc
data.iloc[1:3, 0:3]

date reported_date  current_schools_w_cases
1 2020-09-11    2020-09-14                       15
2 2020-09-14    2020-09-15                       27

Note that when we slice with .iloc, the endpoint are inclusive. (iloc is integer location is same as numpy!)

In [89]:
#Compute mean cases per day
avg_cases = data["new_total_school_related_cases"].mean()
avg_cases

84.89814814814815

We can apply any of these built in functions to multiple columns.

In [90]:
#applying function to multiple rows
data.mean()

current_schools_w_cases                         404.305556
current_schools_closed                            4.888889
current_total_number_schools                   4828.000000
new_total_school_related_cases                   84.898148
new_school_related_student_cases                 61.435185
new_school_related_staff_cases                   12.814815
new_school_related_unspecified_cases             10.849057
recent_total_school_related_cases               754.595745
recent_school_related_student_cases             533.212766
recent_school_related_staff_cases               109.936170
recent_school_related_unspecified_cases         111.425532
past_total_school_related_cases                4272.808511
past_school_related_student_cases              2837.085106
past_school_related_staff_cases                 634.234043
past_school_related_unspecified_cases           801.478723
cumulative_school_related_cases                4394.314815
cumulative_school_related_student_cases        2942.1851

As you can see, the end result is a series, where the column names become the index of the series. The **describe()** method gives you key stats (as a dataframe) for every numeric column.

In [91]:
#Using the describe() method
summary = data.describe()
summary

current_schools_w_cases  current_schools_closed  \
count               108.000000              108.000000   
mean                404.305556                4.888889   
std                 302.603700                6.273119   
min                   2.000000                0.000000   
25%                  73.000000                1.000000   
50%                 433.000000                2.500000   
75%                 670.000000                5.000000   
max                 976.000000               26.000000   

       current_total_number_schools  new_total_school_related_cases  \
count                         108.0                      108.000000   
mean                         4828.0                       84.898148   
std                             0.0                       72.360977   
min                          4828.0                        0.000000   
25%                          4828.0                       22.750000   
50%                          4828.0                       74.500000   
75%                          4828.0                      121.250000   
max                          4828.0                      333.000000   

       new_school_related_student_cases  new_school_related_staff_cases  \
count                        108.000000                      108.000000   
mean                          61.435185                       12.814815   
std                           60.549705                       11.837804   
min                            0.000000                        0.000000   
25%                           15.250000                        4.000000   
50%                           49.000000                       10.000000   
75%                           86.750000                       21.000000   
max                          278.000000                       55.000000   

       new_school_related_unspecified_cases  \
count                            106.000000   
mean                              10.849057   
std                               15.080604   
min                                0.000000   
25%                                0.000000   
50%                                2.000000   
75%                               19.750000   
max                               65.000000   

       recent_total_school_related_cases  recent_school_related_student_cases  \
count                          94.000000                            94.000000   
mean                          754.595745                           533.212766   
std                           553.847895                           449.084514   
min                             3.000000                             2.000000   
25%                           162.500000                           128.750000   
50%                           795.500000                           478.500000   
75%                          1142.500000                           717.250000   
max                          1844.000000                          1533.000000   

       recent_school_related_staff_cases  \
count                          94.000000   
mean                          109.936170   
std                            92.085725   
min                             0.000000   
25%                            27.250000   
50%                            97.500000   
75%                           160.250000   
max                           304.000000   

       recent_school_related_unspecified_cases  \
count                                94.000000   
mean                                111.425532   
std                                 129.900333   
min                                   0.000000   
25%                                   4.250000   
50%                                  22.000000   
75%                                 236.750000   
max                                 354.000000   

       past_total_school_related_cases  past_school_related_student_cases  \
count                        94.000000                          94.000000   
mean        

We can index and slice the above dataframe like any other dataframe.

Next, we look at how to create new columns

In [99]:
#Create a New Column that is a function of other columns
data["Percent_Cases"] = data["current_schools_w_cases"]/4828*100
data.tail()

collected_date reported_date  current_schools_w_cases  \
103     2021-02-25    2021-02-26                      468   
104     2021-02-26    2021-03-01                      530   
105     2021-03-01    2021-03-02                      640   
106     2021-03-02    2021-03-03                      672   
107     2021-03-03    2021-03-04                      683   

     current_schools_closed  current_total_number_schools  \
103                      18                          4828   
104                      20                          4828   
105                      23                          4828   
106                      24                          4828   
107                      26                          4828   

     new_total_school_related_cases  new_school_related_student_cases  \
103                             101                                89   
104                             116                                99   
105                             262                               231   
106                             160                               138   
107                             101                                77   

     new_school_related_staff_cases  new_school_related_unspecified_cases  \
103                              12                                   0.0   
104                              15                                   2.0   
105                              30                                   1.0   
106                              21                                   1.0   
107                              21                                   3.0   

     recent_total_school_related_cases      ...        \
103                              735.0      ...         
104                              844.0      ...         
105                             1072.0      ...         
106                             1141.0      ...         
107                             1168.0      ...         

     recent_school_related_unspecified_cases  past_total_school_related_cases  \
103                                      7.0                           7717.0   
104                                      9.0                           7719.0   
105                                     10.0                           7741.0   
106                                     10.0                           7811.0   
107                                     13.0                           7881.0   

     past_school_related_student_cases  past_school_related_staff_cases  \
103                             5326.0                           1267.0   
104                             5328.0                           1267.0   
105                             5349.0                           1268.0   
106                             5412.0                           1274.0   
107                             5464.0                           1292.0   

     past_school_related_unspecified_cases  cumulative_school_related_cases  \
103                                 1124.0                             8452   
104                                 1124.0                             8563   
105                                 1124.0                             8813   
106                                 1125.0                             8952   
107                                 1125.0                             9049   

     cumulative_school_related_student_cases  \
103                                     5946   
104                                     6043   
105                                     6262   
106                                     6379   
107                                     6455   

     cumulative_school_related_staff_cases  \
103                                   1375   
104                                   1387   
105                                   1417   
106                                   1438   
107                                   1456   

     cumulative_school_related_unspecified_cas

In [100]:
#Delete Columns
data.drop(["new_school_related_staff_cases","new_total_school_related_cases","new_school_related_student_cases","new_school_related_unspecified_cases"], inplace = True, axis=1)
data.head()

collected_date reported_date  current_schools_w_cases  \
0     2020-09-10    2020-09-11                       13   
1     2020-09-11    2020-09-14                       15   
2     2020-09-14    2020-09-15                       27   
3     2020-09-15    2020-09-16                       35   
4     2020-09-16    2020-09-17                       51   

   current_schools_closed  current_total_number_schools  \
0                       0                          4828   
1                       0                          4828   
2                       0                          4828   
3                       0                          4828   
4                       1                          4828   

   recent_total_school_related_cases  recent_school_related_student_cases  \
0                                NaN                                  NaN   
1                                NaN                                  NaN   
2                                NaN                                  NaN   
3                                NaN                                  NaN   
4                                NaN                                  NaN   

   recent_school_related_staff_cases  recent_school_related_unspecified_cases  \
0                                NaN                                      NaN   
1                                NaN                                      NaN   
2                                NaN                                      NaN   
3                                NaN                                      NaN   
4                                NaN                                      NaN   

   past_total_school_related_cases  past_school_related_student_cases  \
0                              NaN                                NaN   
1                              NaN                                NaN   
2                              NaN                                NaN   
3                              NaN                                NaN   
4                              NaN                                NaN   

   past_school_related_staff_cases  past_school_related_unspecified_cases  \
0                              NaN                                    NaN   
1                              NaN                                    NaN   
2                              NaN                                    NaN   
3                              NaN                                    NaN   
4                              NaN                                    NaN   

   cumulative_school_related_cases  cumulative_school_related_student_cases  \
0                               13                                        4   
1                               15                                        5   
2                               29                                        9   
3                               41                                       15   
4                               62                                       20   

   cumulative_school_related_staff_cases  \
0                                      9   
1                                     10   
2                                     14   
3                                     18   
4                                     22   

   cumulative_school_related_unspecified_cases  Percent_Cases  
0                                          NaN       0.269263  
1                                          NaN       0.310688  
2                                          6.0       0.559238  
3                                          8.0       0.724938  
4                                         20.0       1.056338

The inplace argument works as follows:

 - inplace = True : The dataframe itself will have the given column(s) deleted.
 - inplace = False: Will return a dataframe with the column(s) deleted.
 
 The axis argument works as follows:
 
 - axis = 1 : delete columns given
 - axis = 0 : delete rows given.

In [101]:
#Reset the column collected_data and reported_date to be a datetime
data["collected_date"] = pd.to_datetime(data["collected_date"]) 

#Now its a datetime object
data.dtypes

collected_date                                 datetime64[ns]
reported_date                                          object
current_schools_w_cases                                 int64
current_schools_closed                                  int64
current_total_number_schools                            int64
recent_total_school_related_cases                     float64
recent_school_related_student_cases                   float64
recent_school_related_staff_cases                     float64
recent_school_related_unspecified_cases               float64
past_total_school_related_cases                       float64
past_school_related_student_cases                     float64
past_school_related_staff_cases                       float64
past_school_related_unspecified_cases                 float64
cumulative_school_related_cases                         int64
cumulative_school_related_student_cases                 int64
cumulative_school_related_staff_cases                   int64
cumulati

Let's look at the first entry of this column, that is now a datetime column

In [102]:
first_entry = data.loc[0,"collected_date"]
first_entry

Timestamp('2020-09-10 00:00:00')

We see that it is a timestamp.  Timestamps have lots of nice attributes that we can extract.

In [103]:
#Get the day
first_entry.day

10

In [104]:
#Get the month
first_entry.month

9

In [107]:
#We can get the weekday name
first_entry.day_name()

'Thursday'

In [108]:
#We can even see if the year is a leap year
first_entry.is_leap_year

True

In [109]:
#Lets add this column in 
data["DOW"] = data["collected_date"].dt.day_name()
data.head()

collected_date reported_date  current_schools_w_cases  \
0     2020-09-10    2020-09-11                       13   
1     2020-09-11    2020-09-14                       15   
2     2020-09-14    2020-09-15                       27   
3     2020-09-15    2020-09-16                       35   
4     2020-09-16    2020-09-17                       51   

   current_schools_closed  current_total_number_schools  \
0                       0                          4828   
1                       0                          4828   
2                       0                          4828   
3                       0                          4828   
4                       1                          4828   

   recent_total_school_related_cases  recent_school_related_student_cases  \
0                                NaN                                  NaN   
1                                NaN                                  NaN   
2                                NaN                                  NaN   
3                                NaN                                  NaN   
4                                NaN                                  NaN   

   recent_school_related_staff_cases  recent_school_related_unspecified_cases  \
0                                NaN                                      NaN   
1                                NaN                                      NaN   
2                                NaN                                      NaN   
3                                NaN                                      NaN   
4                                NaN                                      NaN   

   past_total_school_related_cases  past_school_related_student_cases  \
0                              NaN                                NaN   
1                              NaN                                NaN   
2                              NaN                                NaN   
3                              NaN                                NaN   
4                              NaN                                NaN   

   past_school_related_staff_cases  past_school_related_unspecified_cases  \
0                              NaN                                    NaN   
1                              NaN                                    NaN   
2                              NaN                                    NaN   
3                              NaN                                    NaN   
4                              NaN                                    NaN   

   cumulative_school_related_cases  cumulative_school_related_student_cases  \
0                               13                                        4   
1                               15                                        5   
2                               29                                        9   
3                               41                                       15   
4                               62                                       20   

   cumulative_school_related_staff_cases  \
0                                      9   
1                                     10   
2                                     14   
3                                     18   
4                                     22   

   cumulative_school_related_unspecified_cases  Percent_Cases        DOW  
0                                          NaN       0.269263   Thursday  
1                                          NaN       0.310688     Friday  
2                                          6.0       0.559238     Monday  
3                                          8.0       0.724938    Tuesday  
4                                         20.0       1.056338  Wednesday

In [110]:
#Let's see the most frequent days for parking tickets
data["DOW"].value_counts()

Wednesday    22
Tuesday      22
Thursday     22
Friday       22
Monday       20
Name: DOW, dtype: int64

In [111]:
#Get the column names
data.columns

Index(['collected_date', 'reported_date', 'current_schools_w_cases',
       'current_schools_closed', 'current_total_number_schools',
       'recent_total_school_related_cases',
       'recent_school_related_student_cases',
       'recent_school_related_staff_cases',
       'recent_school_related_unspecified_cases',
       'past_total_school_related_cases', 'past_school_related_student_cases',
       'past_school_related_staff_cases',
       'past_school_related_unspecified_cases',
       'cumulative_school_related_cases',
       'cumulative_school_related_student_cases',
       'cumulative_school_related_staff_cases',
       'cumulative_school_related_unspecified_cases', 'Percent_Cases', 'DOW'],
      dtype='object')

We can change column names through the rename method

In [115]:
#Change the column names
data.rename(columns={"collected_date":"date"}, inplace=True)

data.head()

date reported_date  current_schools_w_cases  current_schools_closed  \
0 2020-09-10    2020-09-11                       13                       0   
1 2020-09-11    2020-09-14                       15                       0   
2 2020-09-14    2020-09-15                       27                       0   
3 2020-09-15    2020-09-16                       35                       0   
4 2020-09-16    2020-09-17                       51                       1   

   current_total_number_schools  recent_total_school_related_cases  \
0                          4828                                NaN   
1                          4828                                NaN   
2                          4828                                NaN   
3                          4828                                NaN   
4                          4828                                NaN   

   recent_school_related_student_cases  recent_school_related_staff_cases  \
0                                  NaN                                NaN   
1                                  NaN                                NaN   
2                                  NaN                                NaN   
3                                  NaN                                NaN   
4                                  NaN                                NaN   

   recent_school_related_unspecified_cases  past_total_school_related_cases  \
0                                      NaN                              NaN   
1                                      NaN                              NaN   
2                                      NaN                              NaN   
3                                      NaN                              NaN   
4                                      NaN                              NaN   

   past_school_related_student_cases  past_school_related_staff_cases  \
0                                NaN                              NaN   
1                                NaN                              NaN   
2                                NaN                              NaN   
3                                NaN                              NaN   
4                                NaN                              NaN   

   past_school_related_unspecified_cases  cumulative_school_related_cases  \
0                                    NaN                               13   
1                                    NaN                               15   
2                                    NaN                               29   
3                                    NaN                               41   
4                                    NaN                               62   

   cumulative_school_related_student_cases  \
0                                        4   
1                                        5   
2                                        9   
3                                       15   
4                                       20   

   cumulative_school_related_staff_cases  \
0                                      9   
1                                     10   
2                                     14   
3                                     18   
4                                     22   

   cumulative_school_related_unspecified_cases  Percent_Cases        DOW  
0                                          NaN       0.269263   Thursday  
1                                          NaN       0.310688     Friday  
2                                          6.0       0.559238     Monday  
3                                          8.0       0.724938    Tuesday  
4                                         20.0       1.056338  Wednesday

The format for the columns input is {"old_column_name":"new_column_name"}. It should be noted that the rename method can also be applied to change the index by changing columns to index.